### ISSUE TITLE
Search is enabled on all pages

### ISSUE THREAD

**Issue by typaulhus** [cyberark/conjur#119]
Users must be able to search all pages of CE documentation site.

**Comment by mizziness** [comment]
@typaulhus  @jvanderhoof  @brikelly  I looked into this a fair amount and here are my findings:

Because the site output is static HTML, we are limited in what we can use for searching (most local or installed search software uses the database, but we have none.)  Our options include:

* Use a free Jekyll search plugin
  * Free!
  * We would need to add all searchable meta info to the front matter manually on every page, creating extensive manual labor
  * Updates to search indexes are manual (see above)
* Use a free JS search plugin
  * Free!
  * This option is exceedingly slow, OR requires manual search indexing creation, OR both
  * We would need to add all searchable meta info into a search index file in most cases, creating extensive manual labor
  * Updates to search indexes are manual (see above)
* Use Google Custom Search
  * Search results will contain Google ads
  * This would require set-up and tweaking to get working the way we would want
  * Could only test searches on the live site, not in local, making dev and testing very difficult
* Use a paid Jekyll search plugin
  * Monthly fees
  * Set-up required but seems easy
  * Indexing is automatic but requires commands to be added to the build scripts (no big deal, really, but more invasive) 
  * Testing can be done locally because the indexes are generated at build time

**Comment by jvanderhoof** [comment]
This issue was moved to cyberark/conjur-org#280
