### ISSUE TITLE
The Ruby client library is available on rubygems as a pre-release

### ISSUE THREAD

**Issue by brikelly** [cyberark/conjur#188]

**Comment by jtuttle** [comment]
https://github.com/cyberark/conjur-api-ruby/pull/117

**Comment by dustinmm80** [comment]
I am working to have this ready Tuesday AM. 

Then we will have [`conjur-api==5.0.0.pre`](https://github.com/cyberark/conjur-api-ruby/blob/master/CHANGELOG.md) [released](https://rubygems.org/gems/conjur-api).
We should then work on getting Jenkins happy and get `conjur-api==5.0.0` on pushed to RubyGems.

I started work on this as followup to [conjur-api PR #118](https://github.com/cyberark/conjur-api-ruby/pull/118#issuecomment-323188996) but ran into issues with release-bot. I tried to resolve them all today, but didn't get to it. `conjur-rack==3.0.0` [needs to be published to RubyGems](https://github.com/conjurinc/conjur-rack/blob/master/CHANGELOG.md#v300pre) before `conjur-api==5.0.0` because `conjur-api` depends on `conjur-rack`. They are both public Ruby gems.

Once `conjur-api==5.0.0` is on RubyGems we can fix the Gemfiles in `conjur` and `conjur-cli` to point to `conjur-api==5.0.0` on RubyGems.

Then we can publish `conjur-cli==6.0.0.pre` to RubyGems. We need these Jenkins build passing before we publish `conjur-cli==6.0.0.pre: 
- https://jenkins.conjur.net/job/cyberark--conjur/job/master/
- https://jenkins.conjur.net/job/cyberark--conjur-cli/

Once we're satisfied with `conjur-cli==6.0.0.pre` we can publish `conjur-cli==6.0.0.pre`. We should blog about this as we go if we want. It would be nice to have several blog posts. go out in the next few weeks instead of just the one big one.
