### ISSUE TITLE
Add partial list of troubleshooting steps for authn-k8s

### ISSUE THREAD

**Issue by diverdane** [cyberark/conjur#1890]
## Is your feature request related to a problem? Please describe.

It would be good to start collecting troubleshooting information to help
debugging Conjur authn-k8s authentication. Note that there is already
a conjur-docs issue filed for this:

https://app.zenhub.com/workspaces/community-and-integrations-team-5e28ab8f700a191286d5abe0/issues/cyberark/conjur-docs/958

But this is for a more comprehensive, exhaustive list of troubleshooting
steps, and we'd like to start compiling a helpful list in Github as a
placeholder. It may be that the addition of a more official and
comprehensive troubleshooting guide in conjur-docs will supersede
(or perhaps draw on) whatever list we compile here in Github, but
we need to start compiling this list somewhere.

## Describe the solution you would like

A good first pass, possibly partial, list of potential errors that might be
encountered when using Conjur authn-k8s, and also instructions on how to
further diagnose or recover from these errors is included in the cyberark/conjur
Github page. This can even be just a placeholder for starting documentation
that will ultimately be included in an official, more comprehensive troubleshooting
guide in conjur-docs.

**Comment by izgeri** [comment]
AC:
- [ ] Create a place in this repo in MD for adding new authn-k8s troubleshooting scenarios, using the template already in place [here](https://github.com/cyberark/secretless-broker/wiki/Troubleshooting-Guide#template-for-adding-new-troubleshooting-scenarios)
- [ ] Add some initial troubleshooting scenarios for using authn-k8s with Conjur OSS
- [ ] Link to the troubleshooting from cyberark/conjur-docs#958, so that TWs can add this to the official docs if they find the content valuable / when they have time
