### ISSUE TITLE
Conjur returns 500 error on badly encoded Basic Auth token

### ISSUE THREAD

**Issue by telday** [cyberark/conjur#1990]
## Summary
Sending a badly encoded basic authentication token to Conjur will cause the server to error and return a 500 error.

## Steps to Reproduce
Start a Conjur instance and make a request with a bad  basic auth token
e.g.
`curl -H "Authorization: Basic 0g==" http://conjur/authn/dev/login`

## Expected Results
Conjur should return a nice error letting the user what went wrong. In this case I was expecting a 422.

## Actual Results (including error logs, if applicable)
The server errors and returns ugly HTML along with a 500.

## Reproducible
   * [x] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible
   
## Version/Tag number
Using the `conjur:edge` docker image.

**Comment by jvanderhoof** [comment]
Example of how to issue a curl command w/ a username/password: https://github.com/conjurdemos/conjur-intro/blob/main/artifacts/api-client/api-script#L43

**Comment by foxefj-cyber** [comment]
The 500 is thrown because the audit logging is unable to determine the role from the invalid basic authorization header passed in.  It tries to pick it apart in Role::roleid_from_username.  I have fixed the issue by checking if we actually have credentials before trying to use them.
```
    def roleid_from_username(account, login)
      tokens = login.split('/', 2)
```

The expected result says to return a 422, but I propose we actually return a 401 because this is just another form of invalid login.  Thoughts?

**Comment by jvanderhoof** [comment]
@foxefj-cyber, I think `401` makes more sense given the 401 specification:

> The HyperText Transfer Protocol (HTTP) 401 Unauthorized client error status response code indicates that the client request has not been completed because it lacks valid authentication credentials for the requested resource.

A malformed authorization token means the request cannot be authenticated successfully.
