### ISSUE TITLE
Aligning field to use ‘role’ under ‘subject'

### ISSUE THREAD

**Issue by egvili** [cyberark/conjur#2014]
## Summary
All logs have `role` field under subject, except logs of `change password` which names this field `user`.
Please align it to `role` as well

## Expected Results
`role` field under subject section

## Actual Results (including error logs, if applicable)
`user` field under subject section

## Reproducible
   * [X] Always 
   * [ ] Sometimes
   * [ ] Non-Reproducible

**Comment by boazmichaely** [comment]
@alexkalish is this a breaking change for DAP customers?

**Comment by alexkalish** [comment]
@boazmichaely: I would redirect your questions to @netacoral, as this is a changed planned and developed under her direction.

**Comment by boazmichaely** [comment]
ok, so the question is for you  @netacoral  :-)

**Comment by netacoral** [comment]
@boazmichaely the goal of this issue was to align the audit log fields and keep them consistent overall. This does introduce one breaking change to the [audit log of  'Change you password' API action](https://docs.cyberark.com/Product-Doc/OnlineHelp/AAM-DAP/Latest/en/Content/Operations/Services/Audit/dap-audit-events.htm?tocpath=Administration%7CAudit%20Logs%20and%20Events%7C_____2#Changepassword). For all other API actions audit we only added information, and didn't break any existing logs. Let me know if you have any further questions.

**Comment by egvili** [comment]
Fixed in  #2013
