### ISSUE TITLE
Enabled authenticators can be configured using configuration file

### ISSUE THREAD

**Issue by jtuttle** [cyberark/conjur#2173]
Add an `:authenticators` attribute to the `Conjur::ConjurConfig` object. It should default to an empty string and should be validated to ensure it's a comma-separated list of strings starting w/ "authn-".

Update `Authentication::InstalledAuthenticators` to use read the authenticators attribute from `ConjurConfig` instead of the `CONJUR_AUTHENTICATORS` environment variable.

Tests
- update spec / integration tests for Authentication::InstalledAuthenticators

**Comment by kvanblarcum** [comment]
I am confused by the wording within this story. With Trusted Proxy, the precedence was established to be CONJUR env variable >>> config file >>> old env variable.  But the way this story is worded, it appears that the config file will be given a higher precedence. (read the authenticator attribute from conjurconfig instead of the conjur_auth env variable). I think we need to be consistent.

**Comment by h-artzi** [comment]
CONJUR_AUTHENTICATORS env variable >> config file >> database configuration
