### ISSUE TITLE
Description of Vaulting on the Conjur home page makes it sound like Conjur requires EPV to function

### ISSUE THREAD

**Issue by kgilpin** [cyberark/conjur#274]
"CyberArk is the leader in enterprise vaulting, whose Enterprise Password Vault (EPV) is adopted by 50% of the Fortune 100. EPV is the most advanced vault available on the market today, protected by 7 layers of security and providing more than 100 automated password rotators. The CyberArk EPV is extended to the cloud by the Conjur replication architecture and machine identity capabilities, which brings vaulted secrets into the cloud in a scalable and secure way. "

Makes it sound like Conjur is not a standalone project, but rather just an extension of EPV.

**Comment by typaulhus** [comment]
@kgilpin  I'd like to change this to Secrets Management instead of Vaulting:

Secrets Management
Conjur provides a policy framework to manage access to secrets. The policy definitions contain no secret themselves, making them safe and easy to share, review, and edit among a group of people without exposing confidential information.

With secrets abstraction, even the users of secrets need not know their values. By separating development, test, and production rules, policies can be tested in each environment with different secrets and rolled to production with confidence that the application is protected by a least privilege model.

**Comment by jvanderhoof** [comment]
This issue was moved to cyberark/conjur-org#274
