### ISSUE TITLE
CyberArk Logo on .org site

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur#378]
CyberArk Logo on top left corner does not redirect end-user back to CyberArk site when clicked
![cyberarklogo](https://user-images.githubusercontent.com/19418506/30608302-e75db46c-9d45-11e7-95ca-a22713d8a31b.png)

**Comment by ryanprior** [comment]
This is a complicated issue in my view.

On the one hand, it makes sense that clicking a CyberArk logo should take you to the CyberArk website.

On the other hand, people generally expect that clicking the logo in the top left of a website will take them to that website's top level (in this case `conjur.org`) not to some other website.


In my opinion it's a more jarring surprise to be taken elsewhere when clicking in the top left than to be taken to `conjur.org` instead of `cyberark.org` when clicking the CyberArk logo. However, it would be better yet if we could come up with a logo for the top left that looks like it should take you to the website's top-level, which is what almost every top left logo on the Web does.

**Comment by sigalsax** [comment]
We do have a "Welcome" page that can take the user back to the Conjur Homepage. You might be right, I was thinking that "Conjur Enterprise" was not the most intuitive way to get back to CyberArk and usually people click on graphics. 

I agree, we might want to design a graphic with a back arrow in the upper left hand corner that takes you back to the top-level or even back to the Conjur Welcome page.
