### ISSUE TITLE
Blank- Nearly Blank Pages are being Published

### ISSUE THREAD

**Issue by sigalsax** [cyberark/conjur#413]
Nearly blank pages are allowed to be built (by accident). Though there is a job in the continuous integration pipeline to catch blank pages, we need the same job for _nearly_ blank pages as well.

**Comment by sigalsax** [comment]
Course of action:
1) create software that accepts a .html page and returns reports how many words of _content_ are in each
2) create a script that finds all the .html files in the site, runs the content word counter on each, and collects the results into a report
3) create a continuous integration job that runs the blank page checker, reads the report, and fails the build if it isn't clean

**Comment by dustinmm80** [comment]
Do we need software to do this? Seems like it could be solved by PR review

**Comment by ryanprior** [comment]
PR review has missed this issue in the past and we've found out from customers. This would be an automated safety step, like the link checker.

**Comment by sigalsax** [comment]
I am going to complete the first step and submit for review. If needed, we will change course

**Comment by mizziness** [comment]
IMO, this should be something we handle with PRs.  The prior issue wasn't caught during the PR because the review by the coder (myself) and the reviewer (I forget who) wasn't thorough enough.  We should be executing thorough and high-quality reviews, not just of the code that changes, but running the build locally and running through the pages manually.  That isn't always done.
