### ISSUE TITLE
GCP marketplace is updated with latest Conjur OSS release

### ISSUE THREAD

**Issue by brikelly** [cyberark/conjur#820]

**Comment by sgnn7** [comment]
Email chain in progress with all relevant parties CCd. Release repository is not currently being updated with our chart at https://console.cloud.google.com/gcr/images/conjur-cloud-launcher-onboard/GLOBAL/cyberark?login=true (no permissions though) so that's the next thing to figure out here. We pinged our Google contact to let us have visibility into that repo so we are waiting on that right now.

**Comment by sgnn7** [comment]
Blocked on ops to give us the account setup needed and we have not heard anything from google partner contact yet.

**Comment by sgnn7** [comment]
Our side of the marketplace build [seems to work](https://jenkins.conjur.net/job/cyberark--conjur-google-cloud-marketplace/job/master/) now but we're still waiting on the google partner to proceed. Joanne seems to be looking into this. Leaving in blocked but hopefully the development on this issue is done for now.

The image repo is here: https://console.cloud.google.com/gcr/images/conjur-cloud-launcher-onboard/GLOBAL/cyberark

**Comment by sgnn7** [comment]
Removing blocked label - app is on marketplace test endpoint.

Pending in-house testing.
