### ISSUE TITLE
Conjur should be able to clear a variable value

### ISSUE THREAD

**Issue by sgnn7** [cyberark/conjur#919]
We should be able to clear a variable value without policies and without clearing the variable audit history. Current api doesn't allow DELETE and empty/nil POSTs are rejected with 422 on empty values.

AC:
- [ ] Variable value can be set to nothing or empty string

**Comment by jtuttle** [comment]
I think adding a `DELETE` endpoint is probably the safer option here as it makes the deletion very explicit. I worry that if we allow an empty body for the `POST` endpoint we open the door for users accidentally clearing secrets by unintentionally leaving their new secret value out of the request body.

Since we track secret value history in the database, the new endpoint shouldn't actually delete anything. It should instead insert a new secret value that's just a blank string.

**Comment by jtuttle** [comment]
Upon further discussion, closing this for now. @jonahx brought up the valid point that it could have unintended side effects, so unless we have a business case for it, probably not worth adding.

**Comment by jvanderhoof** [comment]
Alternatively, updating to an empty string might be the best-desired outcome.  If we need to remove a variable, that can be done via policy delete.
